name: CI/CD Pipeline
on:
  push:
    branches: [main,master]
  pull-request: 
    branches: [main,master]
env:
  DOCKER_IMAGE_NAME: ci_web_app
jobs:
  buid-and-push:
    runs-on: ubuntu-latest
    steps:
      _name: checkout code 
      _uses: actions/checkout@v3

      _name: Setup docker buildx
      _uses: docker/setup-buildx-action@v3   

      _name: Login to docker hub 
      _users: docker/login-action@v2
      _with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

      _name: build and push docker image
      _uses: docker/build-push-action@v4
      _with:
        contest: .
        push: true
        tag: | 
          ${{secrets.DOCKER_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}:latest 
